In [1]:
#Prints **all** console output, not just last item in cell 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

**Notebook author:** emeinhardt@ucsd.edu

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Overview" data-toc-modified-id="Overview-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Overview</a></span><ul class="toc-item"><li><span><a href="#Usage" data-toc-modified-id="Usage-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Usage</a></span></li><li><span><a href="#Requirements" data-toc-modified-id="Requirements-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Requirements</a></span></li></ul></li><li><span><a href="#Parameters" data-toc-modified-id="Parameters-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Parameters</a></span></li><li><span><a href="#Imports-/-load-data" data-toc-modified-id="Imports-/-load-data-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Imports / load data</a></span></li><li><span><a href="#Main-calculation" data-toc-modified-id="Main-calculation-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Main calculation</a></span></li><li><span><a href="#Export" data-toc-modified-id="Export-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Export</a></span></li></ul></div>

# Overview

Given 
 - a filepath $d$ to an `.npy` file defining a distribution $p(V|C)$ on orthographic wordforms given $n$-gram contexts $C$
 - a filepath prefix $w$ pointing towards an `.npz` file defining a sparse distribution $p(W|V)$ on segmental wordforms given an orthographic wordform $v$ (where $V$ is the same as in $d$)
 - output filepath prefix $o$
 
this notebook calculates $p(W|C)$ and writes it to the filepath $o$ as an `.npy` file.

## Usage

In [ ]:
#FIXME

## Requirements

 - `numpy`
 - the `pydata` `sparse` package

# Parameters

In [2]:
from os import getcwd, chdir, listdir, path, mkdir, makedirs

In [3]:
from boilerplate import *

In [4]:
# Parameters

d = ''
# d = 'LD_Fisher_vocab_in_swbd2003_contexts/LD_fisher_vocab_in_swbd2003_contexts_projected_LTR_newdic_destressed.pV_C.npy'

w = ''
# w = 'LTR_newdic_destressed_aligned_w_GD_AmE_destressed/LTR_newdic_destressed_aligned_CM_filtered_LM_filtered.pW_V.npz'

o = ''
# o = 'LD_Fisher_vocab_in_swbd2003_contexts/LTR_newdic_destressed_aligned_CM_filtered_LM_filtered_in_swbd2003_contexts.pW_C'

In [5]:
ensure_dir_exists(path.dirname(o))

# Imports / load data

In [6]:
from probdist import *

In [7]:
import numpy as np
# import torch
import sparse

In [8]:
# from tqdm import tqdm

In [9]:
# # pVC_mmap = np.memmap(d, dtype='float64', mode='r', shape=new_shape)
# pVC_mmap = np.memmap(d, dtype='float64', mode='r')
# pVC_mmap.shape

In [8]:
# pV_C = np.load(d + '.npy')
pV_C = np.load(d)
pV_C.shape
pV_C.dtype
pV_C.nbytes / 1e9

(9411, 106295)

dtype('float64')

8.00273796

In [35]:
np.sum(pV_C, axis=0) #should all be close to 1
# np.sum(pV_C, axis=1) #nonsense

assert np.allclose(np.sum(pV_C, axis=0), np.ones(shape = np.sum(pV_C, axis=0).shape ))

array([0.70190093, 0.74953535, 0.94330646, ..., 0.75743666, 0.82160234,
       0.68464106])

AssertionError: 

In [9]:
# pW_V = sparse.load_npz(w + '.pW_V.npz')
pW_V = sparse.load_npz(w)
pW_V.shape
pW_V.dtype
pW_V.nbytes / 1e9
pW_V.density

(9172, 9411)

dtype('float64')

0.000225864

0.00010902747492368077

In [33]:
dist_sums = pW_V.sum(axis=0).todense() #should all be 1
dist_sums
assert np.allclose(dist_sums, np.ones(shape=dist_sums.shape))

array([1., 1., 1., ..., 1., 1., 1.])

# Main calculation

In [36]:
pW_C = sparse.matmul(pW_V, pV_C)
pW_C.shape
pW_C.dtype
pW_C.nbytes / 1e9

(9172, 106295)

dtype('float64')

7.79950192

In [14]:
# np.sum(pV_C, axis=0)
# np.sum(pV_C, axis=1) #nonsense

array([0.70190093, 0.74953535, 0.94330646, ..., 0.75743666, 0.82160234,
       0.68464106])

In [13]:
np.sum(pW_C, axis=0)
# np.sum(pW_C, axis=1) #nonsense
assert np.allclose(np.sum(pW_C, axis=0), np.ones(shape = np.sum(pW_C, axis=0).shape) )

array([0.70190093, 0.74953535, 0.94330646, ..., 0.75743666, 0.82160234,
       0.68464106])

# Export

In [ ]:
np.save(o, pW_C)

In [ ]:
o

In [ ]:
listdir(path.dirname(o))